language: java

#command to install dependencies
before_install:
  - export GAE_SDK_VERSION=1.9.46
  - wget http://storage.googleapis.com/appengine-sdks/featured/appengine-java-sdk-${GAE_SDK_VERSION}.zip -nv -P /tmp/
  - mkdir -p ~/appengine-java-sdk
  - unzip /tmp/appengine-java-sdk-${GAE_SDK_VERSION}.zip -d ~/appengine-java-sdks/
  - rm -rf /tmp/appengine-java-sdk-${GAE_SDK_VERSION}.zip
  - export PATH=~/appengine-java-sdks/appengine-java-sdk-${GAE_SDK_VERSION}/bin:${PATH}

install:
  - "mvn clean install"

#command to deploy
after_success:
  - cd liste-envies-war
  - echo ${GOOGLE_CLIENT_SECRET} > client-secret.json
  - appcfg.sh --service_account_json_key_file=client-secret.json -A ${CLOUDSDK_CORE_PROJECT} -V ${TRAVIS_BRANCH} update target/liste-envies-war-2016-SNAPSHOT
